name = "editable-map-api"
main = "index.js"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "MAP_DATA"
id = "你的_KV_ID"

# ====== R2（暂时可不建） ======
# [[r2_buckets]]
# binding = "PHOTO_BUCKET"
# bucket_name = "editable-map-photos"
